### ISSUE TITLE
Use filename as id instead of have it inside migration script

### ISSUE THREAD

**Issue by marcusberro** [eberhara/mongration#12]
Would be good to have filename as step id instead of an id written by developer

**Comment by wmartins** [comment]
@marcusberro what do you think to have both file name and developer id in migration persisted object?

What do you think @eberhara?

**Comment by marcusberro** [comment]
@wmartins @eberhara I've experienced some mistakes using Mongration with more than one migration scripts. For example, when you have similar scripts that you copy and rename the file, developers can forget to change the id. I guess that would be great to constraint the id just on filename and I'm not sure if it is a good idea to keep both option.

**Comment by eberhara** [comment]
Closing since we agreed that assuming a step id by its file name is not a good practice.
